services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "${SERVER_PORT}:3000"
    volumes:
      - ./packages/backend:/app/packages/backend
      - /app/packages/backend/node_modules
    networks:
      - project-network
    profiles:
      - dev

  db:
    image: postgres:13-alpine
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${DB_PORT}:5432"
    networks:
      - project-network
    profiles:
      - dev

  cms-frontend:
    build:
      context: .
      dockerfile: docker/cms-frontend.Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    depends_on:
      - backend
      - db
    env_file:
      - ./.env
    ports:
      - "${CMS_FRONTEND_PORT}:5173"
    volumes:
      - ./packages/cms-frontend:/app/packages/cms-frontend
      - /app/packages/cms-frontend/node_modules
    networks:
      - project-network
    profiles:
      - dev

  test-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    profiles:
      - test

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    healthcheck:
      test:
        ["CMD-SHELL", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "4566:4566"
    profiles:
      - test

networks:
  project-network:
    driver: bridge
