export enum GenreErrorCode {
  NOT_ENOUGH_TRANSLATIONS = "NOT_ENOUGH_TRANSLATIONS",
  DUPLICATE_NAME = "DUPLICATE_NAME",
  NOT_FOUND = "NOT_FOUND",
  IN_USE = "IN_USE",
  INVALID_INPUT_DATA = "INVALID_INPUT_DATA",
}
