export enum SeriesErrorCode {
  NOT_ENOUGH_TRANSLATIONS = "NOT_ENOUGH_TRANSLATIONS",
  NO_TRANSLATIONS_PROVIDED = "NO_TRANSLATIONS_PROVIDED",
  DUPLICATE_TITLE = "DUPLICATE_TITLE",
  NOT_FOUND = "NOT_FOUND",
  IN_USE = "IN_USE",
  INVALID_INPUT_DATA = "INVALID_INPUT_DATA",
}
