/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const afterAll: typeof import('vitest')['afterAll']
  const afterEach: typeof import('vitest')['afterEach']
  const assert: typeof import('vitest')['assert']
  const beforeAll: typeof import('vitest')['beforeAll']
  const beforeEach: typeof import('vitest')['beforeEach']
  const chai: typeof import('vitest')['chai']
  const describe: typeof import('vitest')['describe']
  const expect: typeof import('vitest')['expect']
  const fireEvent: typeof import('@testing-library/react')['fireEvent']
  const it: typeof import('vitest')['it']
  const render: typeof import('@testing-library/react')['render']
  const screen: typeof import('@testing-library/react')['screen']
  const suite: typeof import('vitest')['suite']
  const test: typeof import('vitest')['test']
  const userEvent: typeof import('@testing-library/user-event')['default']
  const vi: typeof import('vitest')['vi']
  const vitest: typeof import('vitest')['vitest']
}
