/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const act: (typeof import("@testing-library/react"))["act"];
  const afterAll: (typeof import("vitest"))["afterAll"];
  const afterEach: (typeof import("vitest"))["afterEach"];
  const assert: (typeof import("vitest"))["assert"];
  const beforeAll: (typeof import("vitest"))["beforeAll"];
  const beforeEach: (typeof import("vitest"))["beforeEach"];
  const chai: (typeof import("vitest"))["chai"];
  const cleanup: (typeof import("@testing-library/react"))["cleanup"];
  const describe: (typeof import("vitest"))["describe"];
  const expect: (typeof import("vitest"))["expect"];
  const fireEvent: (typeof import("@testing-library/react"))["fireEvent"];
  const it: (typeof import("vitest"))["it"];
  const reactScreen: (typeof import("@testing-library/react"))["screen"];
  const render: (typeof import("@testing-library/react"))["render"];
  const renderHook: (typeof import("@testing-library/react"))["renderHook"];
  const suite: (typeof import("vitest"))["suite"];
  const test: (typeof import("vitest"))["test"];
  const toBeChecked: (typeof import("@testing-library/jest-dom"))["toBeChecked"];
  const toBeDisabled: (typeof import("@testing-library/jest-dom"))["toBeDisabled"];
  const toBeEmptyDOMElement: (typeof import("@testing-library/jest-dom"))["toBeEmptyDOMElement"];
  const toBeEnabled: (typeof import("@testing-library/jest-dom"))["toBeEnabled"];
  const toBeFocused: (typeof import("@testing-library/jest-dom"))["toBeFocused"];
  const toBeInTheDocument: (typeof import("@testing-library/jest-dom"))["toBeInTheDocument"];
  const toBeVisible: (typeof import("@testing-library/jest-dom"))["toBeVisible"];
  const toContainElement: (typeof import("@testing-library/jest-dom"))["toContainElement"];
  const toContainHTML: (typeof import("@testing-library/jest-dom"))["toContainHTML"];
  const toHaveAccessibleName: (typeof import("@testing-library/jest-dom"))["toHaveAccessibleName"];
  const toHaveAttribute: (typeof import("@testing-library/jest-dom"))["toHaveAttribute"];
  const toHaveClass: (typeof import("@testing-library/jest-dom"))["toHaveClass"];
  const toHaveDisplayValue: (typeof import("@testing-library/jest-dom"))["toHaveDisplayValue"];
  const toHaveFormValues: (typeof import("@testing-library/jest-dom"))["toHaveFormValues"];
  const toHaveStyle: (typeof import("@testing-library/jest-dom"))["toHaveStyle"];
  const toHaveTextContent: (typeof import("@testing-library/jest-dom"))["toHaveTextContent"];
  const toHaveValue: (typeof import("@testing-library/jest-dom"))["toHaveValue"];
  const userEvent: (typeof import("@testing-library/user-event"))["default"];
  const vi: (typeof import("vitest"))["vi"];
  const vitest: (typeof import("vitest"))["vitest"];
  const waitFor: (typeof import("@testing-library/react"))["waitFor"];
  const waitForElementToBeRemoved: (typeof import("@testing-library/react"))["waitForElementToBeRemoved"];
  const within: (typeof import("@testing-library/react"))["within"];
}
