export enum ArtworkErrorCode {
  // 이미지 업로드 관련
  IMAGE_NOT_PROVIDED = "UPLOAD_SIZE_EXCEEDED",
  IMAGE_EXTENSION_NOT_SUPPORTED = "INVALID_FILE_TYPE",
  IMAGE_SIZE_TOO_LARGE = "UPLOAD_FAILED",
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",

  // 메타데이터 관련
  NOT_EXISTING_GENRES_INCLUDED = "NOT_EXISTING_GENRES_INCLUDED",
  INVALID_INPUT_DATA = "INVALID_INPUT_DATA",
}
