name: CD

on:
  push:
    branches:
      # - "main"
      - "**"
    paths-ignore:
      - "**/*.md"
      - ".vscode/**"
      - "docker-compose.yml"
      - ".github/**"
      - "!.github/workflows/cd.yml" # 편의를 위해, 본 워크플로우의 변경 시에는 트리거되도록

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.check-changes.outputs.packages }}
      migrations: ${{ steps.check-migration.outputs.migrations }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.10.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"
      - name: Detect which packages are changed
        id: check-changes
        uses: ./.github/actions/detect-changes
        with:
          base-ref: ${{ github.event.before }}
      - name: Check Migration Changes
        uses: ./.github/actions/check-migration
        id: check-migration
        with:
          base-ref: ${{ github.event.before }}

  deploy-backend:
    needs: [detect-changes]
    # if: ${{ contains(fromJson(needs.detect-changes.outputs.packages), 'backend') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Log Migration Details
        if: ${{ needs.detect-changes.outputs.migrations == 'true' }}
        run: |
          echo "### Database Migration Execution" >> $GITHUB_STEP_SUMMARY
          echo "Migration will be executed with the following changes:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          git diff --name-only ${{ github.event.before }} HEAD -- packages/backend/src/migrations/ >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
      - name: Run Database Migration
        if: ${{ needs.detect-changes.outputs.migrations == 'true' }}
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_MIGRATION_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true # 마이그레이션 완료까지 대기
      - name: Deploy Backend
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true # 배포 완료까지 대기

  deploy-cms-frontend:
    needs: [detect-changes]
    # if: ${{ contains(fromJson(needs.detect-changes.outputs.packages), 'cms-frontend') }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy CMS Frontend
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_CMS_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true

  deploy-fanarts-frontend:
    needs: [detect-changes]
    # if: ${{ contains(fromJson(needs.detect-changes.outputs.packages), 'fanarts-frontend') }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Fanarts Frontend
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_FANARTS_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
