name: Keep Services Alive

on:
  schedule:
    - cron: "0/14 * * * *"

jobs:
  ping-services:
    runs-on: ubuntu-latest
    steps:
      - name: Ping All Services (Optimized)
        run: |
          curl -s "https://minhoyun.life/api/health/liveness" > /dev/null &
          curl -s "https://cms.minhoyun.life" > /dev/null &
          curl -s "https://fanarts.minhoyun.life" > /dev/null &
          wait

          echo "All services pinged at $(date)"
