name: Check Migration Changes
description: Detects changes in migration files

inputs:
  base-ref:
    description: Base reference to compare changes against
    required: true

outputs:
  migrations:
    description: Whether migration files have changed
    value: ${{ steps.check.outputs.migrations }}

runs:
  using: composite
  steps:
    - id: check
      shell: bash
      run: |
        if git diff --name-only ${{ inputs.base-ref }} HEAD | grep -q "^packages/backend/src/migrations/"; then
          echo "migrations=true" >> $GITHUB_OUTPUT
        else
          echo "migrations=false" >> $GITHUB_OUTPUT
        fi
